### ISSUE TITLE
[Question] Is index also append-only?

### ISSUE THREAD

**Issue by tezheng** [hoteltonight/shameless#4]
Thanks for the repo and instructions, great inspiration!

However, I get a question regarding index updating.

I notice that there is a function "prevent_readonly_attribute_mutation", does this mean that all fields in index can not be altered?

What if I wanna to check the room availability, and create an index to make the search faster, say
index do
  room_id
  availability
end

How can I change the availability when the customer check in/out a room? Shall I directly change the index?

**Comment by exviva** [comment]
Hi @tezheng , you can't change the index values of an existing record, because they're used for lookup. You'll need to create a new record with new index values.
